"""gamification

Revision ID: 1a86bad220fa
Revises: 5f6a64f16f72
Create Date: 2026-02-22 19:44:46.931711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a86bad220fa'
down_revision: Union[str, None] = '5f6a64f16f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('streak', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_activity_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('ui_language', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('notification_time', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_time')
    op.drop_column('users', 'ui_language')
    op.drop_column('users', 'last_activity_date')
    op.drop_column('users', 'streak')
    op.drop_column('users', 'level')
    op.drop_column('users', 'xp')
    # ### end Alembic commands ###
