"""Initial schema

Revision ID: 5f6a64f16f72
Revises: 
Create Date: 2026-02-22 15:36:30.767539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f6a64f16f72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poems', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('poems', 'language',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('poems', 'difficulty',
               existing_type=sa.SMALLINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('poems', 'themes',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='array_to_json(themes)::jsonb')
    op.drop_index(op.f('ix_poems_author'), table_name='poems')
    op.drop_index(op.f('ix_poems_language'), table_name='poems')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_poems_language'), 'poems', ['language'], unique=False)
    op.create_index(op.f('ix_poems_author'), 'poems', ['author'], unique=False)
    op.alter_column('poems', 'themes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.alter_column('poems', 'difficulty',
               existing_type=sa.Float(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('poems', 'language',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('poems', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
